FROM ubuntu

#Com uso de Cache
#RUN apt update
#RUN apt install net-tools --yes
#RUN apt install vim --yes
#RUN apt install curl --yes

#Sem uso de Cache
RUN apt update && apt install net-tools --yes && apt install vim --yes && apt install curl --yes